name: Deploy Site
on:
  push:
    branches: ["master"]
jobs:
  deploy:
    name: Deploy the website
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
      - uses: actions/checkout@v1
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Node JS
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Do the Deployment
        run: |
          npm install
          export NODE_ENV=production
          npm run build
          npm run export
          git checkout -b release
          git pull origin release
          rm -v -rf !\(\".git\"\|\"out\"\)
          cp -a ./out/. ./
          rm -rf ./out
          git config user.name \"Rusith\"
          git config user.email \"rusith@mail.com\"
          git add .
          git commit -m "${{github.event.head_commit.message}}" .
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release

          
